### ISSUE TITLE
Workspace inheritance fails with 'dioxus serve'

### ISSUE THREAD

**Issue by marcerhans** [DioxusLabs/cli#101]
Using 'dioxus serve' with the following project does not work due to inherited workspace fields not being handled correctly.

> **Cargo.toml**
> ```toml
> [workspace]
> 
> [workspace.package]
> authors = ["marcerhans"]
> 
> [package]
> name = "foo"
> version = "0.1.0"
> edition = "2021"
> authors = { workspace = true }
> # (It DOES work if we dupblicate "authors = ["marcerhans"]")
> 
> [dependencies]
> dioxus = "0.3.1"
> dioxus-web = { version = "0.3.0" }
> ```

> **main.rs**
> ```Rust
> #![allow(non_snake_case)]
> 
> use dioxus::prelude::*;
> 
> fn main() {
>     dioxus_web::launch(App);
> }
> 
> fn App(cx: Scope) -> Element {
>     cx.render(rsx! {
>         h1 { "Hello! "}
>     })
> }
> ```

> **Output**
> $ RUST_BACKTRACE=1 dioxus serve
> [WARN] Config file: `Dioxus.toml` not found; using default config.
> [WARN] Config file: `Dioxus.toml` not found; using default config.
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Parse(Error { inner: ErrorInner { kind: Custom, line: Some(9), col: 10, at: Some(127), message: "invalid type: map, expected a sequence", key: ["package", "authors"] } })', /home/${USER}/.cargo/registry/src/github.com-1ecc6299db9ec823/dioxus-cli-0.3.0/src/config.rs:167:68
> stack backtrace:
>    0: rust_begin_unwind
>              at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
>    1: core::panicking::panic_fmt
>              at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
>    2: core::result::unwrap_failed
>              at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
>    3: dioxus_cli::config::CrateConfig::new
>    4: tokio::runtime::park::CachedParkThread::block_on
>    5: dioxus::main
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

> **Output (full)**
> $ RUST_BACKTRACE=full dioxus serve
> [WARN] Config file: `Dioxus.toml` not found; using default config.
> [WARN] Config file: `Dioxus.toml` not found; using default config.
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Parse(Error { inner: ErrorInner { kind: Custom, line: Some(9), col: 10, at: Some(127), message: "invalid type: map, expected a sequence", key: ["package", "authors"] } })', /home/${USER}/.cargo/registry/src/github.com-1ecc6299db9ec823/dioxus-cli-0.3.0/src/config.rs:167:68
> stack backtrace:
>    0:     0x560730bbfc5a - std::backtrace_rs::backtrace::libunwind::trace::h79937bc171ada62c
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
>    1:     0x560730bbfc5a - std::backtrace_rs::backtrace::trace_unsynchronized::h2292bca8571cb919
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
>    2:     0x560730bbfc5a - std::sys_common::backtrace::_print_fmt::h9c461f248e4ae90d
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:65:5
>    3:     0x560730bbfc5a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he9fe6bf1a39182e1
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:44:22
>    4:     0x560730be974e - core::fmt::write::h032658c119c720d7
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/fmt/mod.rs:1208:17
>    5:     0x560730bb8ed5 - std::io::Write::write_fmt::h299fc90dfae41c0d
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/io/mod.rs:1682:15
>    6:     0x560730bbfa25 - std::sys_common::backtrace::_print::heb70d25df9937e3f
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:47:5
>    7:     0x560730bbfa25 - std::sys_common::backtrace::print::had745c0a76b8b521
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:34:9
>    8:     0x560730bc120f - std::panicking::default_hook::{{closure}}::h1ea782cdfa2fd097
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:267:22
>    9:     0x560730bc0f4b - std::panicking::default_hook::h1cc3af63455a163c
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:286:9
>   10:     0x560730bc191c - std::panicking::rust_panic_with_hook::h5cafdc4b3bfd5528
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:688:13
>   11:     0x560730bc16b9 - std::panicking::begin_panic_handler::{{closure}}::hf31c60f40775892c
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:579:13
>   12:     0x560730bc010c - std::sys_common::backtrace::__rust_end_short_backtrace::h28a5c7be595826cd
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:137:18
>   13:     0x560730bc13c2 - rust_begin_unwind
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
>   14:     0x56073007d823 - core::panicking::panic_fmt::h8fa27a0b37dd98b7
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
>   15:     0x56073007dcb3 - core::result::unwrap_failed::h62abf61e411aaa08
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
>   16:     0x56073021f339 - dioxus_cli::config::CrateConfig::new::h92df98f0d3d5c925
>   17:     0x5607300bae72 - tokio::runtime::park::CachedParkThread::block_on::h179def9cc8da9f31
>   18:     0x56073009d762 - dioxus::main::hdce9ffa04f2b2797
>   19:     0x560730142de6 - std::sys_common::backtrace::__rust_begin_short_backtrace::h3cd0b0da591dec0c
>   20:     0x560730135a85 - std::rt::lang_start::{{closure}}::h1ab017dfd0c410b8
>   21:     0x560730bb235c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hfa1c3687c9a20bb8
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/ops/function.rs:606:13
>   22:     0x560730bb235c - std::panicking::try::do_call::h0497133ebe1341e5
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
>   23:     0x560730bb235c - std::panicking::try::h6c3de05c7ca5d07f
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
>   24:     0x560730bb235c - std::panic::catch_unwind::h969058ecb5334b30
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
>   25:     0x560730bb235c - std::rt::lang_start_internal::{{closure}}::h0de6d98cafb42a58
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148:48
>   26:     0x560730bb235c - std::panicking::try::do_call::h77301dcf43953993
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:483:40
>   27:     0x560730bb235c - std::panicking::try::h45b05523a2fe135a
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:447:19
>   28:     0x560730bb235c - std::panic::catch_unwind::hd95cea544b2b9bd2
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panic.rs:137:14
>   29:     0x560730bb235c - std::rt::lang_start_internal::hd16e6ff7bf05a444
>                                at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/rt.rs:148:20
>   30:     0x56073009d9c5 - main
>   31:     0x7fc1c036a510 - __libc_start_call_main
>   32:     0x7fc1c036a5c9 - __libc_start_main@GLIBC_2.2.5
>   33:     0x56073007de95 - _start
>   34:                0x0 - <unknown>

**Comment by mrchantey** [comment]
Are workspaces supported? I can't find any documentation on it.
