### ISSUE TITLE
`dioxus translate` and `dioxus fmt` result in panic

### ISSUE THREAD

**Issue by alice-werefox** [DioxusLabs/cli#126]
Hey! I've been messing around with Dioxus for a bit and I can't seem to get either the `dioxus translate` or `dioxus fmt` commands working. I have some code here: https://gitea.werefox.cafe/ada/dioxus-letter-werefox-cafe/src/branch/main/src/lib.rs

This project runs just fine with `dioxus serve`, so I'm pretty sure it's not something to do with the project itself, however if I try something like `dioxus fmt -f src/lib.rs`, I get the following error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected `!`")', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/dioxus-autofmt-0.3.0/src/lib.rs:46:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
There's a similar story with running something like `dioxus translate -f test.html`, where `test.html` contains:
```
<!DOCTYPE html>
<html>
  <body>
    <h1>My First Heading</h1>
    <p>My first paragraph.</p>
  </body>
</html>
```
This results in the following error:
```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/dioxus-autofmt-0.3.0/src/element.rs:279:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Some output that might be helpful, and you should be able to see the rest of the code if it's relevant here from that link I shared.
```
> rustup -V    
rustup 1.25.2 (17db695f1 2023-02-01)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.68.1 (8460ca823 2023-03-20)`

> dioxus --version
dioxus 0.3.1

>

> dioxus config format-print       
DioxusConfig {
    application: ApplicationConfig {
        name: "rust-letter",
        default_platform: "web",
        out_dir: Some(
            "dist",
        ),
        asset_dir: Some(
            "public",
        ),
        tools: None,
        sub_package: None,
    },
    web: WebConfig {
        app: WebAppConfig {
            title: Some(
                "A Letter For You! 🖤",
            ),
            base_path: None,
        },
        proxy: None,
        watcher: WebWatcherConfig {
            watch_path: Some(
                [
                    "src",
                    "public",
                ],
            ),
            reload_html: Some(
                true,
            ),
            index_on_404: None,
        },
        resource: WebResourceConfig {
            dev: WebDevResourceConfig {
                style: None,
                script: Some(
                    [],
                ),
            },
            style: Some(
                [
                    "tailwind.min.css",
                ],
            ),
            script: Some(
                [],
            ),
        },
    },
    plugin: Boolean(
        true,
    ),
}

**Comment by alice-werefox** [comment]
This is now a duplicate of https://github.com/DioxusLabs/cli/issues/126
