### ISSUE TITLE
How to run an example?

### ISSUE THREAD

**Issue by zoechi** [DioxusLabs/cli#134]
`dioxus` has a parameter `--example` but I haven't found how to make it load an example.

I tried `dioxus serve --example foo`
with `my_project/examples/foo.rs` and `my_project/examples/foo/main.rs`
All I was able to get was 
```
❯ dioxus serve --example foo
[WARN] You appear to be creating a Dioxus project from scratch; we will use the default config
thread 'main' panicked at 'No lib found from cargo metadata', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-cli-0.3.1/src/config.rs:196:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Are there any settings or files that are required?

**Comment by zoechi** [comment]
- The directory `public` needs to exist 
```
dioxus serve --example e01_simple
[INFO] 🚅 Running build command...
    Finished dev [unoptimized + debuginfo] target(s) in 0.10s
[INFO] 👑 Build done.
[WARN] failed to parse `name` custom section Invalid name type (at offset 39050190)
[INFO] 🚀 Starting development server...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }), paths: [] }', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-cli-0.3.1/src/server/mod.rs:395:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

- The nightly toolchain is not supported which causes
```
u_datagrid_dioxus_example.js:369 panicked at 'misaligned pointer dereference: address must be a multiple of 0x4 but is 0x113fdd', /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dioxus-interpreter-js-0.3.1/src/sledgehammer_bindings.rs:5:1

Stack:

Error
    at http://localhost:8080/assets/dioxus/bwu_datagrid_dioxus_example.js:372:17
    at logError (http://localhost:8080/assets/dioxus/bwu_datagrid_dioxus_example.js:222:18)
    at imports.wbg.__wbg_new_abda76e883ba8a5f (http://localhost:8080/assets/dioxus/bwu_datagrid_dioxus_example.js:371:62)
    at console_error_panic_hook::Error::new::h747f129be748f100 (http://localhost:8080/assets/dioxus/bwu_datagrid_dioxus_example_bg.wasm:wasm-function[6260]:0x1c97b5)
    at console_error_panic_hook::hook_impl::hd718eae470609917 (http://localhost:8080/assets/dioxus/bwu_datagrid_dioxus_example_bg.wasm:wasm-function[1147]:0x106b4e)
    at console_error_panic_hook::hook::h4fdf0d66edff6bd5 (http://localhost:8080/assets/dioxus/bwu_datagrid_dioxus_example_bg.wasm:wasm-function[6859]:0x1d1a8c)
    at core::ops::function::Fn::call::hee2c86b1e59e0c37 (http://localhost:8080/assets/dioxus/bwu_datagrid_dioxus_example_bg.wasm:wasm-function[5903]:0x1c3f28)
    at std::panicking::rust_panic_with_hook::h3335d5ae7b6e707f (http://localhost:8080/assets/dioxus/bwu_datagrid_dioxus_example_bg.wasm:wasm-function[2521]:0x16504a)
    at std::panicking::begin_panic_handler::{{closure}}::h5a8755a4515288e5 (http://localhost:8080/assets/dioxus/bwu_datagrid_dioxus_example_bg.wasm:wasm-function[3073]:0x17e13e)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h379fad7ab97fa8de (http://localhost:8080/assets/dioxus/bwu_datagrid_dioxus_example_bg.wasm:wasm-function[7973]:0x1dbfc5)


(anonymous) @ bwu_datagrid_dioxus_example.js:369
logError @ bwu_datagrid_dioxus_example.js:222
imports.wbg.__wbg_error_f851667af71bcfc6 @ bwu_datagrid_dioxus_example.js:366
$console_error_panic_hook::error::hedaccd6c85e2376d @ bwu_datagrid_dioxus_example_bg.wasm:0x1a8fdc
$console_error_panic_hook::hook_impl::hd718eae470609917 @ bwu_datagrid_dioxus_example_bg.wasm:0x106c3a
$console_error_panic_hook::hook::h4fdf0d66edff6bd5 @ bwu_datagrid_dioxus_example_bg.wasm:0x1d1a8c
$core::ops::function::Fn::call::hee2c86b1e59e0c37 @ bwu_datagrid_dioxus_example_bg.wasm:0x1c3f28
$std::panicking::rust_panic_with_hook::h3335d5ae7b6e707f @ bwu_datagrid_dioxus_example_bg.wasm:0x16504a
$std::panicking::begin_panic_handler::{{closure}}::h5a8755a4515288e5 @ bwu_datagrid_dioxus_example_bg.wasm:0x17e13e
$std::sys_common::backtrace::__rust_end_short_backtrace::h379fad7ab97fa8de @ bwu_datagrid_dioxus_example_bg.wasm:0x1dbfc5
$rust_begin_unwind @ bwu_datagrid_dioxus_example_bg.wasm:0x1b20cf
$core::panicking::panic_fmt::he89c91536ec9fb76 @ bwu_datagrid_dioxus_example_bg.wasm:0x1cfee1
$core::panicking::panic_misaligned_pointer_dereference::h1d73e18be6736360 @ bwu_datagrid_dioxus_example_bg.wasm:0x169e5f
$dioxus_interpreter_js::sledgehammer_bindings::Channel::flush::h74602bd6ae8dc1c3 @ bwu_datagrid_dioxus_example_bg.wasm:0x6053c
$dioxus_web::dom::WebsysDom::apply_edits::ha8bdb770f7d48336 @ bwu_datagrid_dioxus_example_bg.wasm:0x3a222
$dioxus_web::run_with_props::{{closure}}::hdb084082cec2f013 @ bwu_datagrid_dioxus_example_bg.wasm:0x17ff9
$wasm_bindgen_futures::task::singlethread::Task::run::h1ba0395d52630208 @ bwu_datagrid_dioxus_example_bg.wasm:0xe0f06
$wasm_bindgen_futures::queue::QueueState::run_all::h0058859246c9f651 @ bwu_datagrid_dioxus_example_bg.wasm:0xc3254
$wasm_bindgen_futures::queue::Queue::new::{{closure}}::h5fa5cf7105bfcb68 @ bwu_datagrid_dioxus_example_bg.wasm:0x1957f7
$<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h6ad4c17fa5df3e8f @ bwu_datagrid_dioxus_example_bg.wasm:0x1669c9
__wbg_adapter_28 @ bwu_datagrid_dioxus_example.js:266
real @ bwu_datagrid_dioxus_example.js:205
Promise.then (async)
(anonymous) @ bwu_datagrid_dioxus_example.js:925
logError @ bwu_datagrid_dioxus_example.js:222
imports.wbg.__wbg_then_ec5db6d509eb475f @ bwu_datagrid_dioxus_example.js:924
$js_sys::Promise::then::h8bedfe0cdf1c8cff @ bwu_datagrid_dioxus_example_bg.wasm:0x1a20ca
$wasm_bindgen_futures::queue::Queue::schedule_task::hac7d452f8c748513 @ bwu_datagrid_dioxus_example_bg.wasm:0x10af37
$wasm_bindgen_futures::task::singlethread::Task::spawn::{{closure}}::he4797d519a967c18 @ bwu_datagrid_dioxus_example_bg.wasm:0x1c96d2
$std::thread::local::LocalKey<T>::try_with::h2a711be9ef74cf48 @ bwu_datagrid_dioxus_example_bg.wasm:0x111da8
$std::thread::local::LocalKey<T>::with::h9eedb341392c5d83 @ bwu_datagrid_dioxus_example_bg.wasm:0x173029
$wasm_bindgen_futures::task::singlethread::Task::spawn::hcb03797948b4f84d @ bwu_datagrid_dioxus_example_bg.wasm:0xc1e99
$wasm_bindgen_futures::spawn_local::h74ea3c1a4afb0643 @ bwu_datagrid_dioxus_example_bg.wasm:0x1a5145
$dioxus_web::launch_with_props::h5a784a394c3ba089 @ bwu_datagrid_dioxus_example_bg.wasm:0x1c013c
$dioxus_web::launch::h903ef18dfb368c18 @ bwu_datagrid_dioxus_example_bg.wasm:0x1c258e
$e01_simple::main::h323c3bff39dc6ee4 @ bwu_datagrid_dioxus_example_bg.wasm:0x1a64d2
$core::ops::function::FnOnce::call_once::h402e7f5f7067a671 @ bwu_datagrid_dioxus_example_bg.wasm:0x1cff7a
$std::sys_common::backtrace::__rust_begin_short_backtrace::h4edc609818d2e66a @ bwu_datagrid_dioxus_example_bg.wasm:0x1cff46
$std::rt::lang_start::{{closure}}::hb69682e38f55132b @ bwu_datagrid_dioxus_example_bg.wasm:0x19e324
$std::rt::lang_start_internal::h1153fc1ac0085fa7 @ bwu_datagrid_dioxus_example_bg.wasm:0x118cb9
$std::rt::lang_start::hced4a5bbb52e5686 @ bwu_datagrid_dioxus_example_bg.wasm:0x18b2e5
$main @ bwu_datagrid_dioxus_example_bg.wasm:0x1da165
$__wbindgen_start @ bwu_datagrid_dioxus_example_bg.wasm:0x1dbc61
finalizeInit @ bwu_datagrid_dioxus_example.js:1007
init @ bwu_datagrid_dioxus_example.js:1037
await in init (async)
(anonymous) @ (index):14
bwu_datagrid_dioxus_example_bg.wasm:0x1dc086 Uncaught (in promise) RuntimeError: unreachable
    at __rust_start_panic (bwu_datagrid_dioxus_example_bg.wasm:0x1dc086)
    at rust_panic (bwu_datagrid_dioxus_example_bg.wasm:0x1dbb85)
    at std::panicking::rust_panic_with_hook::h3335d5ae7b6e707f (bwu_datagrid_dioxus_example_bg.wasm:0x165075)
    at std::panicking::begin_panic_handler::{{closure}}::h5a8755a4515288e5 (bwu_datagrid_dioxus_example_bg.wasm:0x17e13e)
    at std::sys_common::backtrace::__rust_end_short_backtrace::h379fad7ab97fa8de (bwu_datagrid_dioxus_example_bg.wasm:0x1dbfc5)
    at rust_begin_unwind (bwu_datagrid_dioxus_example_bg.wasm:0x1b20cf)
    at core::panicking::panic_fmt::he89c91536ec9fb76 (bwu_datagrid_dioxus_example_bg.wasm:0x1cfee1)
    at core::panicking::panic_misaligned_pointer_dereference::h1d73e18be6736360 (bwu_datagrid_dioxus_example_bg.wasm:0x169e5f)
    at dioxus_interpreter_js::sledgehammer_bindings::Channel::flush::h74602bd6ae8dc1c3 (bwu_datagrid_dioxus_example_bg.wasm:0x6053c)
    at dioxus_web::dom::WebsysDom::apply_edits::ha8bdb770f7d48336 (bwu_datagrid_dioxus_example_bg.wasm:0x3a222)
$__rust_start_panic @ bwu_datagrid_dioxus_example_bg.wasm:0x1dc086
$rust_panic @ bwu_datagrid_dioxus_example_bg.wasm:0x1dbb85
$std::panicking::rust_panic_with_hook::h3335d5ae7b6e707f @ bwu_datagrid_dioxus_example_bg.wasm:0x165075
$std::panicking::begin_panic_handler::{{closure}}::h5a8755a4515288e5 @ bwu_datagrid_dioxus_example_bg.wasm:0x17e13e
$std::sys_common::backtrace::__rust_end_short_backtrace::h379fad7ab97fa8de @ bwu_datagrid_dioxus_example_bg.wasm:0x1dbfc5
$rust_begin_unwind @ bwu_datagrid_dioxus_example_bg.wasm:0x1b20cf
$core::panicking::panic_fmt::he89c91536ec9fb76 @ bwu_datagrid_dioxus_example_bg.wasm:0x1cfee1
$core::panicking::panic_misaligned_pointer_dereference::h1d73e18be6736360 @ bwu_datagrid_dioxus_example_bg.wasm:0x169e5f
$dioxus_interpreter_js::sledgehammer_bindings::Channel::flush::h74602bd6ae8dc1c3 @ bwu_datagrid_dioxus_example_bg.wasm:0x6053c
$dioxus_web::dom::WebsysDom::apply_edits::ha8bdb770f7d48336 @ bwu_datagrid_dioxus_example_bg.wasm:0x3a222
$dioxus_web::run_with_props::{{closure}}::hdb084082cec2f013 @ bwu_datagrid_dioxus_example_bg.wasm:0x17ff9
$wasm_bindgen_futures::task::singlethread::Task::run::h1ba0395d52630208 @ bwu_datagrid_dioxus_example_bg.wasm:0xe0f06
$wasm_bindgen_futures::queue::QueueState::run_all::h0058859246c9f651 @ bwu_datagrid_dioxus_example_bg.wasm:0xc3254
$wasm_bindgen_futures::queue::Queue::new::{{closure}}::h5fa5cf7105bfcb68 @ bwu_datagrid_dioxus_example_bg.wasm:0x1957f7
$<dyn core::ops::function::FnMut<(A,)>+Output = R as wasm_bindgen::closure::WasmClosure>::describe::invoke::h6ad4c17fa5df3e8f @ bwu_datagrid_dioxus_example_bg.wasm:0x1669c9
__wbg_adapter_28 @ bwu_datagrid_dioxus_example.js:266
real @ bwu_datagrid_dioxus_example.js:205
Promise.then (async)
(anonymous) @ bwu_datagrid_dioxus_example.js:925
logError @ bwu_datagrid_dioxus_example.js:222
imports.wbg.__wbg_then_ec5db6d509eb475f @ bwu_datagrid_dioxus_example.js:924
$js_sys::Promise::then::h8bedfe0cdf1c8cff @ bwu_datagrid_dioxus_example_bg.wasm:0x1a20ca
$wasm_bindgen_futures::queue::Queue::schedule_task::hac7d452f8c748513 @ bwu_datagrid_dioxus_example_bg.wasm:0x10af37
$wasm_bindgen_futures::task::singlethread::Task::spawn::{{closure}}::he4797d519a967c18 @ bwu_datagrid_dioxus_example_bg.wasm:0x1c96d2
$std::thread::local::LocalKey<T>::try_with::h2a711be9ef74cf48 @ bwu_datagrid_dioxus_example_bg.wasm:0x111da8
$std::thread::local::LocalKey<T>::with::h9eedb341392c5d83 @ bwu_datagrid_dioxus_example_bg.wasm:0x173029
$wasm_bindgen_futures::task::singlethread::Task::spawn::hcb03797948b4f84d @ bwu_datagrid_dioxus_example_bg.wasm:0xc1e99
$wasm_bindgen_futures::spawn_local::h74ea3c1a4afb0643 @ bwu_datagrid_dioxus_example_bg.wasm:0x1a5145
$dioxus_web::launch_with_props::h5a784a394c3ba089 @ bwu_datagrid_dioxus_example_bg.wasm:0x1c013c
$dioxus_web::launch::h903ef18dfb368c18 @ bwu_datagrid_dioxus_example_bg.wasm:0x1c258e
$e01_simple::main::h323c3bff39dc6ee4 @ bwu_datagrid_dioxus_example_bg.wasm:0x1a64d2
$core::ops::function::FnOnce::call_once::h402e7f5f7067a671 @ bwu_datagrid_dioxus_example_bg.wasm:0x1cff7a
$std::sys_common::backtrace::__rust_begin_short_backtrace::h4edc609818d2e66a @ bwu_datagrid_dioxus_example_bg.wasm:0x1cff46
$std::rt::lang_start::{{closure}}::hb69682e38f55132b @ bwu_datagrid_dioxus_example_bg.wasm:0x19e324
$std::rt::lang_start_internal::h1153fc1ac0085fa7 @ bwu_datagrid_dioxus_example_bg.wasm:0x118cb9
$std::rt::lang_start::hced4a5bbb52e5686 @ bwu_datagrid_dioxus_example_bg.wasm:0x18b2e5
$main @ bwu_datagrid_dioxus_example_bg.wasm:0x1da165
$__wbindgen_start @ bwu_datagrid_dioxus_example_bg.wasm:0x1dbc61
finalizeInit @ bwu_datagrid_dioxus_example.js:1007
init @ bwu_datagrid_dioxus_example.js:1037
await in init (async)
(anonymous) @ (index):14
bwu_datagrid_dioxus_example.js:661 WebSocket connection to 'ws://localhost:8080/_dioxus/hot_reload' failed: 
(
```

**Comment by zoechi** [comment]
@Demonthos thanks for the feedback!
What is a good place to post questions about Dioxus?

**Comment by Demonthos** [comment]
> @Demonthos thanks for the feedback! What is a good place to post questions about Dioxus?

You can [Join the discord](https://discord.gg/9MtSMpsH) and ask a question in the help chat or use the discussions in the main Dioxus repo. This was definitely a bug (just one that has been fixed), so opening an issue for it was fine
